package com.abelhzo.generate.jpa.h2.entities;
// Generated 20 jun. 2023 22:18:56 by Hibernate Tools 6.2.4.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "ROLES", schema = "PUBLIC", catalog = "MYDATABASE")
public class Rol implements java.io.Serializable {

	private static final long serialVersionUID = 1007700142632900356L;
	private Integer idRol;
	private String rol;

	public Rol() {
	}

	public Rol(String rol) {
		this.rol = rol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID_ROL", unique = true, nullable = false)
	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Column(name = "ROL", nullable = false, length = 30)
	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

}
