package com.abelhzo.generate.jpa.h2.entities;
// Generated 17 jun. 2023 01:56:49 by Hibernate Tools 6.2.4.Final

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIOS", schema = "PUBLIC", catalog = "MYDATABASE", uniqueConstraints = @UniqueConstraint(columnNames = "USERNAME"))
public class Usuario implements java.io.Serializable {

	private static final long serialVersionUID = -911068773420188558L;
	private Long idUsuario;
	private String username;
	private String contrase;
	private String email;
	private Date nacimiento;
	private byte[] foto;
	private Timestamp creado;
	private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

	public Usuario() {
	}

	public Usuario(Long idUsuario, String username, String contrase, String email, Date nacimiento, byte[] foto,
			Timestamp creado, Set<UsuarioRol> usuarioRols) {
		this.idUsuario = idUsuario;
		this.username = username;
		this.contrase = contrase;
		this.email = email;
		this.nacimiento = nacimiento;
		this.foto = foto;
		this.creado = creado;
		this.usuarioRols = usuarioRols;
	}

	@Id
	@Column(name = "ID_USUARIO", unique = true, nullable = false)
	public Long getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Long idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 70)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "CONTRASE", nullable = false, length = 80)
	public String getContrase() {
		return this.contrase;
	}

	public void setContrase(String contrase) {
		this.contrase = contrase;
	}

	@Column(name = "EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NACIMIENTO", nullable = false, length = 10)
	public Date getNacimiento() {
		return this.nacimiento;
	}

	public void setNacimiento(Date nacimiento) {
		this.nacimiento = nacimiento;
	}

	@Column(name = "FOTO")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREADO", nullable = false, length = 26)
	public Timestamp getCreado() {
		return this.creado;
	}

	public void setCreado(Timestamp creado) {
		this.creado = creado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario", cascade = CascadeType.ALL)
	public Set<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
		this.usuarioRols = usuarioRols;
	}

}
